default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: time_tracker_production
  username: time_tracker
  password: <%= ENV['TIME_TRACKER_DATABASE_PASSWORD'] %>
